name: "gget_gget"
description: gget is a free, open-source command-line tool and Python package that enables efficient querying of genomic databases. gget consists of a collection of separate but interoperable modules, each designed to facilitate one type of database querying in a single line of code.
keywords:
  - gget
  - reference
  - database
  - databases
  - download
tools:
  - "gget":
      description: "gget enables efficient querying of genomic databases"
      homepage: "https://github.com/pachterlab/gget"
      documentation: "https://pachterlab.github.io/gget/"
      tool_dev_url: "https://github.com/pachterlab/gget"
      doi: "10.1093/bioinformatics/btac836"
      licence: "['BSD-2-clause']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - json:
      type: file
      description: JSON output of gget tool
      pattern: "*.json"
  - csv:
      type: file
      description: CSV output of gget tool. Requires --csv option
      pattern: "*.csv"
  - file:
      type: file
      description: Path to any file downloaded by gget
      pattern: "*"

authors:
  - "@adamrtalbot"
