name: "picard_collectinsertsizemetrics"
description: Collects and aggregates insert size metrics
keywords:
  - metrics
  - insert-size
  - quality
  - bam
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      tool_dev_url: https://github.com/broadinstitute/picard/
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: An aligned BAM/SAM file
      pattern: "*.{bam,sam}"
  - fasta:
      type: file
      description: |
        A reference file to calculate dropout metrics measuring reduced representation of reads.
        Optional input.
      pattern: "*.fasta"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - stats:
    type: file
    description: Insert size distribution generated by Picard.
    pattern: "*.txt"

authors:
  - "@adamrtalbot"
