name: "vcf2maf"
description: vcf2maf
keywords:
  - "vcf2maf"
  - annotation
tools:
  - "vcf2maf":
      description: "Convert a VCF into a MAF where each variant is annotated to only one of all possible gene isoforms"
      homepage: "https://github.com/mskcc/vcf2maf"
      documentation: "https://github.com/mskcc/vcf2maf"
      tool_dev_url: "https://github.com/mskcc/vcf2maf"
      doi: "10.5281/zenodo.593251"
      licence: "['Apache-2.0']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: |
        vcf to convert to MAF format. Ideally pre-annotated with VEP. Must be uncompressed.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - maf:
      type: file
      description: MAF file produced from VCF
      pattern: "*.maf"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@adamrtalbot"
